name: Deploy FastAPI App to Azure

on:
  push:
    branches:
      - main

jobs:
  # sets up, builds, tests, and packages for deployment
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      # pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # will add test support later
      # note: sudo apt-get is needed to install pytest properly.
      # something is wrong with it.
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover ./tests

      - name: Upload artifact # uploads build artifact to next job
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact # downloads artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app
          path: .

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # from Azure publish profile
