name: Deploy FastAPI App to Azure

on:
  push:
    branches:
      - main

jobs:
  # sets up, builds, tests, and packages for deployment
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # will add test support later
      # - name: Run tests
      #   run: pytest

      - name: Package app # copies contents to package dir
        run: |
          mkdir -p package
          cp -r main.py requirements.txt package/

      - name: Upload artifact # uploads build artifact to next job
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app
          path: package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact # downloads artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: fastapi-app
          path: package # Extract package

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # from Azure publish profile
          package: package
